### ISSUE TITLE
Transforming body of request before sending

### ISSUE THREAD

**Issue by kristianhasselknippe** [federicotdn/verb#20]
Loving this package!

I'm currently working mainly with a GraphQL API, and finding it would be really nice to express the body of my requests as a GraphQL query block and then transform it, before sending the request, into valid json.

So instead of:
```
* My Query
post /api

{
  "query": "{ myQuery(first: 5){ edges { cursor node { id title creator { id displayName }}}}}"
}
```
something like
```
* My Query
post /api

<<some way of making it accept a graphql query>>
{ 
    myQuery(first: 5) {
       edges { 
           cursor 
           node { 
              id 
 ...
}
```
Perhaps inside a code block in order to get proper syntax highlighting and indentation behavior.

Is this currently possible, and if not, do you have any pointers for where it would make sense to add this kind of support?

**Comment by federicotdn** [comment]
Hey @kristianhasselknippe, thanks for the feedback.

What you're suggesting has, in my opinion, two separate parts. The first one would be to add some kind of post-processing mechanism to requests, so that requests can be modified before they are sent. In your case, it would take the request body and put it inside the JSON object.

The second part is syntax highlighting for request bodies. Luckily that was added very recently after this issue: https://github.com/federicotdn/verb/issues/17. In your case, you would need to find a mode that provides syntax highlighting for GraphQL, which I imagine already exists! With that you can surround your request body with `#+begin_src graphql-mode`/`#+end_src`.

So for the first part, I'm imagining that we could add a new Org property called e.g. `Verb-Apply`, that would allow specifying a function that would process the request before it is sent/exported.  Obviously it would accept any type of function, and in your case you would need to implement one that does GraphQL -> JSON. Your example would then look like this:

- init.el
```elisp
(defun graphql-to-json (rs)
  ;; Modify RS and return it (RS is a request specification, type `verb-request-spec')
  ;; TODO: remove newlines
  (oset rs body (format "{\"query\": \"%s\"}" (oref rs body)))
  rs)
```

- example.org
```org
* My Query
:properties:
:Verb-Apply: graphql-to-json
:end:

post /api
    myQuery(first: 5) {
       edges { 
           cursor 
           node { 
              id 
 ...
}
```

Would something like that work for you?

**Comment by kristianhasselknippe** [comment]
@federicotdn That sounds like it would work very well!

**Comment by federicotdn** [comment]
Ok! I've added a first version of this feature: https://github.com/federicotdn/verb#request-mapping-functions.  It should be available right after the next MELPA build, please check if it works OK for you.

**Comment by kristianhasselknippe** [comment]
Thanks for doing this so fast @federicotdn! I'll give it a try.

**Comment by kristianhasselknippe** [comment]
@federicotdn Works well :) Thanks again!

**Comment by federicotdn** [comment]
Good to hear!
