### ISSUE TITLE
Variables and ob-verb

### ISSUE THREAD

**Issue by mcraveiro** [federicotdn/verb#21]
Hi Verb developers,

thanks very much for an extremely useful mode. I'm upgrading from restclient to it, using ```ob-verb``` in my regular org-mode file. As part of this work, I am also trying to make my setup slightly more secure by setting  sensitive information in ```authinfo.gpg``` file via epa. I've got it all setup as described here [1], which I wrapped into a function called ```get-password```, but now I am struggling to figure out how to supply the password into verb as a variable. I'm afraid I am not very knowledgeable when it comes to lisp. I tried setting up using:

```
#+begin_src verb :verb-var pwd=(get-password "USERNAME") :wrap src ob-verb-response
```

As well as:

```
#+begin_src verb :var pwd=(get-password "USERNAME") :wrap src ob-verb-response
```

I also put the value in property. In all cases, when I do ```{{pwd}}``` inside of my source block, I get variable not defined. What is the correct way of doing this?

Many thanks for your time.

Marco

[1] https://emacs.stackexchange.com/questions/28676/org-mode-header-properties-from-authinfo-gpg

**Comment by federicotdn** [comment]
Hey @mcraveiro, in your example you're making use of two unrelated features, code tags and Babel, so I'll explain them separately.

When writing a request specification, you may add `{{...}}` tags anywhere inside the request. Whatever is contained inside these tags will be evaluated as a Elisp expression. So in your case, you would only need to add `{{(get-password "USERNAME")}}` wherever you need, and when the request is sent, the tag will be evaluated and the value inserted. Here's an example:

```
* My request               :verb:
get http://localhost/api/foobar?user=john&password={{(get-password "john")}}
```

However, you want to have this request wrapped in a Babel source block, presumably to have the responses written to the same file. To do that, simply wrap the contents of the request with `#+begin_src verb` and `#+end_src`:

```
* My request               :verb:
#+begin_src verb :wrap src ob-verb-response
get http://localhost/api/foobar?user=john&password={{(get-password "john")}}
#+end_src
```

What you were trying didn't work, because the `:var` and `:verb-var` Babel source arguments are not parsed by Verb, only `:op` is.

Hope this helps! Let me know if anything else isn't working.

**Comment by mcraveiro** [comment]
Hi @federicotdn ,

Thanks for the prompt response. Followed your suggestion and updated my code to:

```
      <password>{{(get-password "USERNAME")}}</password>
```
And that solved all my problems. I now have a very secure org-mode file :-) Thanks very much for all for the project and your help.
