### ISSUE TITLE
Is there a way to set variables in property blocks or on the top level to be consumed at that or deeper levels?

### ISSUE THREAD

**Issue by dantheobserver** [federicotdn/verb#27]
First and foremost, love this tool! I'm looking for a way in verb to be able to set a property on a certain level via either verb-var and be able to reference it in that level or levels below?  Mainly my use case is that a particular string appears in multiple requests, or the same request multiple times (url/body/etc)

**Comment by federicotdn** [comment]
Hey @dantheobserver, any variables you set via `verb-var` or `verb-set-var` will be globally available for all requests to use. These variables are local to the buffer you are using when either of these functions is called. Feel free to share an example if you need more details on how this works.

**Comment by dantheobserver** [comment]
roughly given this structure
```* API                                                                :verb:
template https://some-api.com/

** api1
template /api1
*** Get api1
GET /?name=={{(verb-var some-id)}}

*** Post some-var
POST

{
  "name": "sample-name",
  "id": {{(verb-var some-id)}},
  "value": test
}
```
instead of relying on one of the previous sets of some-id, I would like to declare it above all of these with a default value, but trying to place a {{(verb-var some-id "123")}} outside of the strings that appear in the actual request doesn't run.

**Comment by federicotdn** [comment]
Ok, that's an interesting use case. Have you tried using `eval` in the file variables section at the end of the file?
```org
# Local Variables:
# eval: (verb-set-var "foo" 123)
# eval: (verb-set-var "bar" 321)
# End:
```

**Comment by dantheobserver** [comment]
That's possible, I figured something more streamlined and integrated with verb in a more idiomatic way.  My proposal perhaps is something like this
```
* API                                                                :verb:
template https://some-api.com/
#perhaps something integrated and stored and passed on with the template
verb/var: some-id "Sample-var"
Accept

** api1
template /api1
*** Get api1
GET /?name=={{(verb-var some-id)}}

*** Post some-var
POST

{
  "name": "sample-name",
  "id": {{(verb-var some-id)}},
  "value": test
}
```

perhaps it's something I can take a look into because some other things I've been using it for include hexifying a string which I'd think would be a great addition to the library,

**Comment by federicotdn** [comment]
The downside of specifying it there is that it could be interpreted as an HTTP header, because an HTTP header's name can be comprised of any number of printable ASCII characters, sans `:`. So in that case it would make the Verb syntax a bit more difficult, because now there would be special cases on how headers are written. I would like to keep the request specifications as close to the actual HTTP content that will be sent as possible (code tags are the obvious exception to this).

My idea is: we use Org keywords at the top of the file to describe variables that should be set globally. For example:
```org
#+VERB-VAR: some-id 1234
#+VERB-VAR: other-var "hello"

* My API Endpoints
GET ...
```

To extract them, we can use something like this:
```elisp
(defun verb-get-global-vars ()
  (org-element-map (org-element-parse-buffer 'element) 'keyword
    (lambda (elem)
      (when-let ((key (org-element-property :key elem)))
        (when (verb--string= key "VERB-VAR")
          (org-element-property :value elem))))))
```
Which will return:
```elisp
("some-id 1234"
 "other-var \"hello\"")
```
Then for each element in the list, we would need to split off the first space-separated element (e.g. `some-id`), treat it as a variable name, and then take everything on the right (e.g. `1234`) and call `read` with it, which should return an Elisp value. Then it would be as simple as calling `(verb-set-var var-name var-value)` for each element in the list. All of this could be executed as soon as `verb-mode` is enabled. What do you think?

**Comment by dantheobserver** [comment]
I like that idea, though scoping the vars nearest to the current request so that they may cascade and override lower levels similar to how verb handles the request templates as well.  But yes, this is probably the better solution

**Comment by hjudt** [comment]
I am also looking for a way to declare variables for requests, possibly inherited to child requests. The README.md tells in section https://github.com/federicotdn/verb#storing-responses-by-key, that "Any properties starting with Verb- (case insensitive) will be added to the request as metadata. Other properties will be ignored". I thought it would be possible to access this metadata in the request, using it as a variable, but so far I have not found how to do it.
For my use case, I'd really need a variable that can be changed easily, so that I do not have to edit all the requests depending on it. My current solution is to add a elisp source block before the request that I can easily evaluate similar to the request itself, but it would be great to have a way to actually set variables like the verb-store property and get it (re-)evaluated automatically each time the request is sent.

**Comment by federicotdn** [comment]
@dantheobserver I think making Verb variables override each other in lower levels is not necessary (plus, it would be difficult to implement since code tags are evaluated after the final request has been computed). It is not necessary because from the examples you shared, it seems like you would always use the exact value in any request heading level. If you wanted to use a different value at a certain level, you can always just use another variable. Obviously let me know if I misinterpreted what you wanted to say.

@hjudt You can always access Org properties starting with `Verb-` via the [request mapping functions](https://github.com/federicotdn/verb#request-mapping-functions). The properties should be exposed in the `metadata` property of the `rs` object (i.e. `(oref rs metadata)`).

If I understand correctly, are you trying to use/create a variable in your requests that depends on the request itself? An example of your setup would help me understand the problem better (and to check if it is the same as @dantheobserver's).

**Comment by dantheobserver** [comment]
I think the vars will work fine, it's just that the entire buffer must be loaded and it isn't directly in the path of the verb flow.  My idea was to have another mechanism with verb to inject constants that are level aware and cascade to whichever request you're making, in real-time without relying on org or emacs specific properties.  I started to look at writing a test and adding it to the org file.  My idea was to have another function that gathers the constants up the chain and inject them with verb-var, wiht a simple regex search at each level's text.    

The use case is very narrow, so the more I think of it it probably for now can just be done in some emacs way, though I'm not well versed on the emacs/org properties and maybe there's a way to evaluate them without loading the buffer?

**Comment by federicotdn** [comment]
That does seem like it is very specific to your setup. Would using simple code tags `{{(some-function ...)}}` with a function you've defined yourself be enough? Maybe Verb variables aren't flexible enough for you case.

**Comment by dantheobserver** [comment]
sorry for the delay, where would the tags go? I'm trying to see if I can eval verb-var somewhere along the lines between the headers and the request but that's not working.

**Comment by federicotdn** [comment]
No problem - I'm closing this issue then, but feel free to open another one if you think there's a general enhancement you think could be useful for the project.

**Comment by bigodel** [comment]
> The downside of specifying it there is that it could be interpreted as an HTTP header, because an HTTP header's name can be comprised of any number of printable ASCII characters, sans `:`. So in that case it would make the Verb syntax a bit more difficult, because now there would be special cases on how headers are written. I would like to keep the request specifications as close to the actual HTTP content that will be sent as possible (code tags are the obvious exception to this).

can i get back to this issue with a suggestion? first and foremost, i LOVE Verb! it allows me to describe API's structure, example usages and documentation all in the same place. i was a user of Restclient before it, but `ob-restclient` doesn't have inheritance like Verb does (at least last time i tried it), so i would have to evaluate each previous code block in the heading hierarchy to have the desired workflow i, which i have by default in Verb. so Verb solved the problem of having to evaluate various code blocks, or having to have a default code block to be evaluated before evaluating everything else -- what i usually would have is a source block with global variables, along with the Login and Authentication type requests, needed for me to proceed using the API i was interacting with.

with Verb all i'm missing is a way to define those global variables i mentioned. as you said, headers are any printable ASCII character sans `:`, which is why Restclient chose to use `:varname = value` to declare its variables. couldn't Verb do something similar? we could even check out this portion of Restclient's implementation to try to emulate it. 

currently i have the same problem as i had before, i need to evaluate a source block to define the `verb-set-var`'s before everything else. yeah, i could define local `eval` forms, but i'd need to add each of them to `safe-local-eval-forms` (it isn't safe allowing any `eval` form to be run in your system...). i could also have a function and/or a source block with various `(verb-set-var ...)` calls, which is what i have currently, but that requires me to manually call this source block or function, whereas with global variables like in Restclient all i need is to write it.

the solution with `#+verb-var` keyword is a great middle ground, and i even improved a bit upon your function (see the end of this comment), but i think we could introduce a new syntax element for global variables to make it more streamlined.

i'd be more than happy to contribute to a possible implementing a new syntax construct for Verb, but i'd need a couple of pointers as to which functions are used for parsing text into Verb objects.

```lisp
(defun verb-get-global-vars ()
  (org-element-map (org-element-parse-buffer 'element) 'keyword
    (lambda (elem)
      (when-let ((key (org-element-property :key elem)))
        (when (verb--string= key "VERB-VAR")
          (let* ((var-str (split-string (org-element-property :value elem) " "))
                 (key (intern (car var-str)))
                 (value (string-join (cdr var-str) " ")))
            (cons key
                  (cond
                   ((not (and (zerop (string-to-number value))
                              (not (string-match-p "0+" value))))
                    (string-to-number value))
                   (t (string-trim value "\"" "\""))))))))))
```
