### ISSUE TITLE
Render HTML response in eww 

### ISSUE THREAD

**Issue by mcraveiro** [federicotdn/verb#37]
Hi verb-mode developers,

Thanks very much for a great mode, which I rely upon daily. I have a question related to how responses are processed. Sometimes our API server replies in HTML (when the request is malformed, etc). Is it possible to select the mode of the response buffer so that these requests get handled by eww [1] by any chance? Its not a big issue really, but I noticed there is a ```verb-json-use-mode``` so I wondered if there is something similar for other response types of res such as HTML.

Many thanks for your time.

Marco

[1] [Emacs Web Wowser](https://www.gnu.org/software/emacs/manual/html_mono/eww.html)

**Comment by federicotdn** [comment]
Hello!

I quickly tried to check if there was an easy way to make EWW a handler for `text/html` responses - but there's a couple of problems, mainly, that EWW does its own buffer handling, and that EWW's internal API has changed across Emacs releases (from 27 to `master`, for example). For this reason I think it might be more trouble than it's worth at the moment.

However, your point made me think that I never tried to integrate Verb to EWW, so I made a quick implementation, which might be useful to you. You can now "export" a request to EWW by using `C-c C-r C-w` (this will open the GET request directly using EWW).

You can also re-send a request you've already sent by going to its Verb response buffer, and pressing `C-c C-r C-w` there. This will re-send the request, but this time display it using EWW. It's cheating a bit, because the request is being sent again (!), but the same URL and query string arguments will be used, including the HTTP headers as well. Let me know if it's useful!

**Comment by federicotdn** [comment]
Closing this as an alternative (hopefully equivalent) solution was added in 2.14.0.

**Comment by mcraveiro** [comment]
Sorry I haven't updated my work elpa yet, its a bit of pain to do it so I only do it infrequently. I will do it and provide feedback, I'll use the alternative. Cheers
