### ISSUE TITLE
Trailing newline characters in body

### ISSUE THREAD

**Issue by rycee** [federicotdn/verb#7]
Thanks for this nice software, I'm using it quite a lot nowadays! One thing that I was struggling with today – for longer than I care to admit – is that any newline after the request body is included in the request. Admittedly this is quite logical but I was still caught by it and perhaps others are as well?

More specifically, consider the document
```
* Test                                                                 :verb:
post https://postman-echo.com/post
content-type: application/x-www-form-urlencoded

foo=foo&bar=bar

* Another heading
```
that is, including a newline character before the next heading. The JSON response includes the received parameters where bar is given the extra newlines:
```json
    "foo": "foo",
    "bar": "bar\n"
```

Changing the document to
```
* Test                                                                 :verb:
post https://postman-echo.com/post
content-type: application/x-www-form-urlencoded

foo=foo&bar=bar
* Another heading
```
gives the response
```
    "foo": "foo",
    "bar": "bar"
```

I'm not sure what to do, perhaps the existing behavior is best. But maye it should be noted as a gotcha somewhere? A similar issue was raised in https://github.com/pashky/restclient.el/issues/71.

**Comment by federicotdn** [comment]
Hey @rycee! Thanks for the detailed report. The behavior you described is expected, the HTTP body is exactly what's below the headers and before the next heading.

The reason it's like this is that I wanted to provide a mechanism to describe HTTP bodies as precisely as possible. The only problem with the solution is that readability is lost, because then you need to stick your headings to the previous HTTP body without any newlines in between.

What I will do is the following: 1) document the current behavior and 2) add a user option for automatically right-trimming whitespace from request bodies.

**Comment by rycee** [comment]
Yeah, in retrospective I agree it is expected behavior. I think your proposed solution with optional trimming is perfect since it would be possible to have space between document sections 🙂

**Comment by federicotdn** [comment]
I've added a new customizable variable `verb-trim-body-end`, it should be available to use on the next MELPA build. Hope it's useful :sunglasses:

**Comment by rycee** [comment]
Thanks! Just tried it and the new option works very well.
