### ISSUE TITLE
Verb is not using proxy

### ISSUE THREAD

**Issue by gopar** [federicotdn/verb#8]
Hey! Thanks for the awesome package.

One thing I've noticed is that when the proxy is set, it won't use it. I verified by hitting `https://api.ipify.org?format=json` when the proxy is configured and getting a diff ip besides the proxy.

I've configured the proxy to be something like the following
```lisp
(setq verb-using-proxy "http://user:pass@0.0.0.0:8080")
```

Any ideas?

Also, any way to configure the use of proxy in the org file like `template` ? Thanks!

**Comment by federicotdn** [comment]
Hey @gopar, thanks for trying that out. I have to admit that I added the proxy variable very early on, without testing it. Now that I've tested it with a local proxy I've realized it doesn't really work as I thought it would. I believe the correct way is this one: https://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html

What I'll do is remove the `verb-using-proxy` variable (as it doesn't really do anything), and add that link to the docs. I've tested setting `url-proxy-services` as described there and it worked correctly.

Also, I'm not sure how HTTP proxies are supposed to work with HTTPS traffic, or how Emacs handles that specifically. So that could be a problem.

Next up would be specifying proxies per-request, but I think that could be much more complicated. I'll look into that in the future if I can.

**Comment by federicotdn** [comment]
Hey @gopar, any news on this? Could you get it to work with your proxy?

**Comment by gopar** [comment]
Hey, wasn't able to get it to work since my proxy requires credentials and figure out how to get it right

**Comment by federicotdn** [comment]
Thanks for testing this. Since this project depends on `url.el`, the only thing I can do for the moment is point at https://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html.
