### ISSUE TITLE
Feature Request - import request from curl

### ISSUE THREAD

**Issue by vinikira** [federicotdn/verb#9]
First, congratulations for this awesome project!

Is there a possibility of make a feature that import from curl to Verb format, like Postman do?

I'd read a bit of code (specifically the export curl function) to try help with a PR, but my Elisp is terrible :disappointed:.

**Comment by federicotdn** [comment]
Hey @vinikira, thanks!!

It should be doable. I was thinking of adding a general import system sometime, so that adding new import functions could be done easily. I was thinking of maybe adding the ability to import OpenAPI specifications, but that would be relatively time consuming. Curl would probably take less time! I've written this down as something to work on in the future.

**Comment by flashcode** [comment]
First thanks @federicotdn for this project, I like it! ❤️ 

For your information, I just wrote a small Emacs package to import Postman collections, as verb or restclient format (which I used before switching to verb).
This was just for my own needs, it does not support (yet) all Postman features (PR are welcome).
The package is available here: https://github.com/flashcode/impostman

**Comment by federicotdn** [comment]
That is great!! I've added it to the README so more users can discover it :+1:

**Comment by federicotdn** [comment]
Closing as I do not plan on implementing this for the meantime. Feel free to reopen with a specific implementation plan or PR!
